### ISSUE TITLE
How can I disable the login/authentication feature?

### ISSUE THREAD

**Issue by themilanfan** [PanJiaChen/vue-element-admin#1294]
I do not require authentication in my application and I'm not quite sure how to remove it.

Please advise,
Thanks!

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/permission.js

remove this.

**Comment by denish-developer** [comment]
I have remove the permission.js file. but now i am unable to view sidebars!

**Comment by EdwardAckerman** [comment]
I spent a few hours on this, I probably didn't do it the right way, but since in my case was a WIP... I will tell you what I did:

Basically in src/permission.js it checks for logged in user (by getting the token set whenever a user is logged in), if user is logged in it renders and adds the routes... If user is not logged in it will redirect to login page (unless page is in whitelist)

if one day you want to enable login feature again, on line 57 of src/permission.js do something like
![image](https://user-images.githubusercontent.com/43795015/79097826-1065c600-7d37-11ea-8d79-8250959b6eec.png)

This way you will still be able to check for logged in user in a future, render the sidebar, commit your role as a "public dummy user" and next() the user :)

This is a veeeeeerryyy ugly/workarround approach btw, I know there are probably better ways

**Comment by MinJi1999** [comment]
@EduardoNakatsuka  hi! I saw your solution, and i changed permission.js part like that(you did in image). And now here is a problem😅. you said `remember to modify store/modules/user.js and set the method used as commit('SET_ROLES', ['public']);`
let me get this straight. so, do i have to change 64 lines(commit('SET_ROLES', roles)) in  modules/user.js to 'commit('SET_ROLES', ['public']);' ?? Please i was right😂😂.
