### ISSUE TITLE
permission.js:36 data functions should return an object

### ISSUE THREAD

**Issue by OrchesAdam** [PanJiaChen/vue-element-admin#1501]
/src/permission.js:36 
`Message.error(err || 'Verification failed, please login again')`
会抛出异常
`data functions should return an object`

或许应该改成 `err.Message`

**Comment by PanJiaChen** [comment]
这个和自己的业务强耦合了，每个公司的错误信息的格式都是不同的，所以需要你自己进行修改。

**Comment by sumantafinarb** [comment]
I'm trying to login and get authenticated to an admin dashboard. When I click Login I get the token back as expected, but then, on console, I see: [Vue warn]: data functions should return an object:, and a list of red lines like this: [Vue warn]: Property "visible" must be accessed with "$data.visible" because properties starting with "$" or "_" are not proxied in the Vue instance to prevent conflicts with Vue internal. (found in ).

And 8 more like this one.

I understand why data needs to be a function and not an object in Vuejs, I searched in Google and I just found clarification on this. But I double checked my code and data is in fact a function returning an object. I don't know then, if all the other warnings below are there because of it. Also, the login, if successful, should redirect to the dashboard page. It actually does (the url on the browser changes), but the view does not update.

Are all these things related?

I am now using a real api, before, with a fake one, everything was working fine. Sorry if for someone this can sound a stupid question, yes I am new to Vue and programming in general, but I don't know what to look at on Google to solve it.

Thank you.

I'm running on localhost, the apis point to a server with a different address (I avoided CORS running Chrome without it). I checked all the data() in my code to be sure there wasn't any of them declared as objects but everything looks fine.
