### ISSUE TITLE
permission.js may  has bug  due to cookie and user in store can forge

### ISSUE THREAD

**Issue by su6838354** [PanJiaChen/vue-element-admin#412]
hi

in permission.js:21
`  if (getToken()) { // determine if there has token`

this cookie is set by js and not httponly, so we can set it even then has no account.

in permission.js:27
` if (store.getters.roles.length === 0) { // 判断当前用户是否已拉取完user_info信息`

we also can dispatch the user info to store

can u help me explain this question

thank u

**Comment by PanJiaChen** [comment]
The answer is Yes, because this project is just an example, its token has only simple characters such as `admin` or `editor`, you can fake it easily.
But in the production environment token is a complex unique uid, can not be simply forged out.
And you can see this function will set token to service to verify permissions.
https://github.com/PanJiaChen/vue-element-admin/blob/3c0696d1a9582924f6987e6db549836933a010f5/src/permission.js#L28-L39
