### ISSUE TITLE
不是，你乱改我vscode配置干嘛，无语

### ISSUE THREAD

**Issue by pbstar** [PanJiaChen/vue-element-admin#4132]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by Shiqi-hulala** [comment]
你他妈是什么东西，我改你配置，你在说什么jb




&nbsp;&nbsp;&nbsp;梦凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanJiaChen/vue-element-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午3:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132)





 
Closed #4132 as not planned.

**Comment by pbstar** [comment]
你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？[.editorconfig](https://github.com/PanJiaChen/vue-element-admin/blob/master/.editorconfig)

**Comment by pbstar** [comment]
> ###

你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？[.editorconfig](https://github.com/PanJiaChen/vue-element-admin/blob/master/.editorconfig)

**Comment by Shiqi-hulala** [comment]
我碰了你这个文件吗？？你直接说我改你配置？？？？




&nbsp;&nbsp;&nbsp;梦凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanJiaChen/vue-element-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午5:37
***@***.***&gt;;
抄送:&nbsp;"   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132)





 
你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？.editorconfig

**Comment by pbstar** [comment]
> 我碰了你这个文件吗？？你直接说我改你配置？？？？ &nbsp;&nbsp;&nbsp;梦凡 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PanJiaChen/vue-element-admin" ***@***.***&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午5:37 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132) 你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？.editorconfig — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你这个文件有问题，拉取下来打开就会影响本地vscode配置

**Comment by Shiqi-hulala** [comment]
我想问 :我是有push 这个&nbsp;&nbsp;vue-element-admin 在github上吗？？
我能改 花裤衩的源码吗？？？&nbsp;
最后 你在哪拉取的 然后出了问题你在给我说？？？




&nbsp;&nbsp;&nbsp;梦凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanJiaChen/vue-element-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午5:41
***@***.***&gt;;
抄送:&nbsp;"   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132)





  
我碰了你这个文件吗？？你直接说我改你配置？？？？ &nbsp;&nbsp;&nbsp;梦凡 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PanJiaChen/vue-element-admin" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午5:37 @.&gt;; 抄送:&nbsp;" @.@.&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132) 你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？.editorconfig — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你这个文件有问题，拉取下来打开就会影响本地vscode配置

**Comment by pbstar** [comment]
> 我想问 :我是有push 这个&nbsp;&nbsp;vue-element-admin 在github上吗？？ 我能改 花裤衩的源码吗？？？&nbsp; 最后 你在哪拉取的 然后出了问题你在给我说？？？ &nbsp;&nbsp;&nbsp;梦凡 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PanJiaChen/vue-element-admin" ***@***.***&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午5:41 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132) 我碰了你这个文件吗？？你直接说我改你配置？？？？ &nbsp;&nbsp;&nbsp;梦凡 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PanJiaChen/vue-element-admin" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午5:37 @.&gt;; 抄送:&nbsp;" @.@.&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132) 你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？.editorconfig — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 你这个文件有问题，拉取下来打开就会影响本地vscode配置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

？我这个不是回复的项目吗，我@你了？

**Comment by Shiqi-hulala** [comment]
我都不知道你在说什么，这个东西发到我都邮箱的我怎么知道你在说什么啊






&nbsp;&nbsp;&nbsp;梦凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanJiaChen/vue-element-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午5:45
***@***.***&gt;;
抄送:&nbsp;"   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132)





  
我想问 :我是有push 这个&nbsp;&nbsp;vue-element-admin 在github上吗？？ 我能改 花裤衩的源码吗？？？&nbsp; 最后 你在哪拉取的 然后出了问题你在给我说？？？ &nbsp;&nbsp;&nbsp;梦凡 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PanJiaChen/vue-element-admin" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午5:41 @.&gt;; 抄送:&nbsp;" @.@.&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132) 我碰了你这个文件吗？？你直接说我改你配置？？？？ &nbsp;&nbsp;&nbsp;梦凡 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PanJiaChen/vue-element-admin" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午5:37 @.&gt;; 抄送:&nbsp;" @.@.&gt;; 主题:&nbsp;Re: [PanJiaChen/vue-element-admin] 不是，你乱改我vscode配置干嘛，无语 (Issue #4132) 你说不是这个文件改的？你又是什么东西？不会说话别说，你妈就教你整天他妈他妈的？.editorconfig — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你这个文件有问题，拉取下来打开就会影响本地vscode配置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
？我这个不是回复的项目吗，我@你了？

**Comment by aote777** [comment]
不是 笑死我了 花裤衩的项目  跟你有啥关系
