### ISSUE TITLE
bug unexpected token < prod

### ISSUE THREAD

**Issue by nacimgoura** [PanJiaChen/vue-element-admin#819]
Hello,
when i launch in production (by not modifying anything) with `npm run build:prod --preview`, i have the error `unexpected token <` at `http://localhost:9526/`.

![capture d ecran 2018-06-29 a 10 35 00](https://user-images.githubusercontent.com/9990521/42082439-3f885608-7b88-11e8-951b-c1d36e0998fe.png)
I did the "npm install" command at first.
I don't see how we can fix that.
Thanks for your help.

**Comment by 727023460** [comment]
我还以为只有我是这样

**Comment by PanJiaChen** [comment]
The reason for this bug is this caused `assetsPublicPath`


https://github.com/PanJiaChen/vue-element-admin/blob/572a2d9c34688e277ac0ed7c1d713060a7c8b1d4/config/index.js#L69

You can temporarily set `assetsPublicPath:'/'`to a to solve this problem.

I will solve this problem gracefully as soon as possible

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-element-admin/commit/e4481a9d3493fffafc8fa30e314abbae897ce6b7

- npm install
- npm run build:prod --preview
